apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-metallb-config
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 1m
  path: ./clusters/hlcl1/infra/network/metallb/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: infra-metallb
  timeout: 5m
